# Deskripsi

## Deskripsi Project
Project ini merupakan salah satu tugas Mini Project pada Kelas Data Science & AI Fundamentals Batch 42 yang diselenggarakan oleh DigitalSkola. Mini Project ini dikerjakan oleh : Khadafi Zubaidi.

Dalam project ini dijelaskan mengenai langkah-langkah untuk membersihkan data, menampilkan data, serta melakukan analisis data eksploratif menggunakan bahasa pemrograman Python dan file data berekstensi csv.

# Import Library

## Penjelasan
Library yang digunakan dalam project ini adalah Pandas. Pandas adalah pustaka Python yang digunakan untuk mengolah data, seperti menganalisis, membersihkan, menjelajahi, dan memanipulasi data. Nama Pandas berasal dari singkatan "Panel Data" dan "Python Data Analysis"

In [6]:
import pandas as pd

# Memanggil Data

## Penjelasan
Setelah dilakukan import library pandas, selanjutnya kita akan memanggil data-data pada file csv kemudian disimpan ke dalam variabel df (dataframe). Hal ini diperlukan untuk pengelolaan data selanjutnya.

In [11]:
df = pd.read_csv('Mobile_phone_price.csv')

Sekarang kita tampilkan isi dari variabel df

In [14]:
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
0,Apple,iPhone 13 Pro,128 GB,6 GB,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256 GB,12 GB,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128 GB,8 GB,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128 GB,6 GB,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128 GB,8 GB,6.4,50 + 12.2,4614,799
...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649

# Informasi Umum Dataframe

## Penjelasan
Untuk melihat informasi umum dari dataframe (df) kita menggunakan metode :
1.   df.shape : untuk mengetahui jumlah baris dan kolom dataframe tersebut
2.   df.info : untuk mengetahui jumlah kolom, label kolom, tipe data setiap kolom
3.   df.describe : untuk mengetahui gambaran umum dari dataframe berupa statistik deskriptif, seperti : jumlah (count), rata-rata (mean), deviasi standar (std), nilai minimum (min), persentil ke-25 (Q1), median (persentil ke-50 atau Q2), persentil ke-75 (Q3) dan nilai maksimum (max)
4.   df.columns : untuk mengetahui judul setiap kolom pada dataframe tersebut

In [19]:
df.shape

(407, 8)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Brand                   407 non-null    object
 1   Model                   407 non-null    object
 2   Storage                 407 non-null    object
 3   RAM                     407 non-null    object
 4   Screen Size (inches)    407 non-null    object
 5   Camera (MP)             407 non-null    object
 6   Battery Capacity (mAh)  407 non-null    int64
 7   Price ($)               407 non-null    object
dtypes: int64(1), object(7)
memory usage: 25.6+ KB

In [23]:
df.describe()

       Battery Capacity (mAh)
count              407.000000
mean              4676.476658
std                797.193713
min               1821.000000
25%               4300.000000
50%               5000.000000
75%               5000.000000
max               7000.000000

In [25]:
df.columns

Index(['Brand', 'Model', 'Storage ', 'RAM ', 'Screen Size (inches)',
       'Camera (MP)', 'Battery Capacity (mAh)', 'Price ($)'],
      dtype='object')

# Analisis

## Penjelasan
Pada bagian ini kita akan melakukan beberapa analisis yaitu : Analisis Kolom Storage, Analisis Kolom RAM, Analisis Kolom Screen Size dan Analisis Kolom Price


---

## Analisis Kolom Storage

In [30]:
## Pertama kita akan melihat nilai unik dari dataframe khususnya pada kolom Storage
df['Storage '].unique()

array(['128 GB', '256 GB', '64 GB', '32 GB', '128GB', '256GB', '64GB',
       '32GB', '256', '64', '128', '512', '32'], dtype=object)

Hasil yang diberikan dari perintah df['Storage '].unique() di atas adalah berupa array dari nilai unik yang ada di kolom Storage. Jika kita melihat bahwa **selain semua tipe data pada kolom Storage masih bertipe object, ada ketidaksamaan isi dari kolom Storage. Dimana ada data yang mengandung kata GB dan tidak. Untuk hal ini maka perlu kita melakukan penghapusan kata GB**. Kode berikut ini adalah contohnya :

In [33]:
s = '128 GB' # Kita definisikan sebuah variabel s dengan nilai string 128<spasi>GB
s = s.replace(' GB', '') # mereplace string '<spasi>GB' dari string variabel s untuk kemudian disimpan kembali dalam variabel s
s # tampilkan isi dari variabel s, hasil yang diberikan adalah 128 saja tanpa GB

'128'

In [35]:
type(s) # cek tipe data dari variabel s

str

Kode berikut berfungsi untuk menghapus kata GB pada data-data dari kolom Storage yang masih mengandung GB. Selain itu juga kita akan melakukan konversi ke dalam tipe data integer untuk data-data di kolom Storage. Konversi ini dibutuhkan agar ketika dilakukan describe pada kolom Storage, dihasilkan gambaran umum berupa statistik deskriptif, seperti : jumlah (count), rata-rata (mean), deviasi standar (std), nilai minimum (min), persentil ke-25 (Q1), median (persentil ke-50 atau Q2), persentil ke-75 (Q3) dan nilai maksimum (max).

In [39]:
df['Storage '] = df['Storage '].str.replace(' ', '')
df['Storage '] = df['Storage '].str.replace('GB', '')
df['Storage '] = df['Storage '].astype(int)

In [41]:
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
0,Apple,iPhone 13 Pro,128,6 GB,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256,12 GB,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128,8 GB,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128,6 GB,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128,8 GB,6.4,50 + 12.2,4614,799
...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649

Sekarang kita akan mengecek tipe data Storage dengan menggunakan perintah df.info

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Brand                   407 non-null    object
 1   Model                   407 non-null    object
 2   Storage                 407 non-null    int64
 3   RAM                     407 non-null    object
 4   Screen Size (inches)    407 non-null    object
 5   Camera (MP)             407 non-null    object
 6   Battery Capacity (mAh)  407 non-null    int64
 7   Price ($)               407 non-null    object
dtypes: int64(2), object(6)
memory usage: 25.6+ KB

Sekarang kita akan mengecek gambaran umum dari dataframe menggunakan df.describe. Disini kita melihat **perbedaan dengan hasil describe pada kode sebelumnya yang hanya menampilkan data statistik deskriptif dari kolom Battery Capacity (mAh) saja, sedangkan describe yang baru juga menampilkan data statistik deskriptif dari kolom Storage**

In [47]:
df.describe()

         Storage   Battery Capacity (mAh)
count  407.000000              407.000000
mean   123.046683             4676.476658
std     64.963160              797.193713
min     32.000000             1821.000000
25%     64.000000             4300.000000
50%    128.000000             5000.000000
75%    128.000000             5000.000000
max    512.000000             7000.000000

## Analisis Kolom RAM

In [50]:
## Pertama kita akan melihat nilai unik dari dataframe khususnya pada kolom RAM
df['RAM '].unique()

array(['6 GB', '12 GB', '8 GB', '4 GB', '3 GB', '2 GB', '4GB', '8GB',
       '6GB', '12GB', '3GB', '2GB', '5GB', '12', '3', '6', '8', '4', '16',
       '2'], dtype=object)

Hasil yang diberikan dari perintah df['RAM '].unique() di atas adalah berupa array dari nilai unik yang ada di kolom RAM. Jika kita melihat bahwa selain semua tipe data pada kolom RAM masih bertipe object, ada ketidaksamaan isi dari kolom RAM. Dimana ada data yang mengandung kata GB dan tidak. Untuk hal ini maka perlu kita melakukan penghapusan kata GB pada semua data-data dari kolom RAM yang masih mengandung GB. Selain itu juga kita akan melakukan konversi ke dalam tipe data integer untuk data-data di kolom RAM

In [53]:
df['RAM '] = df['RAM '].str.replace(' ', '')
df['RAM '] = df['RAM '].str.replace('GB', '')
df['RAM '] = df['RAM '].astype(int)

Sekarang kita akan mengecek tipe data RAM dengan menggunakan perintah df.info

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Brand                   407 non-null    object
 1   Model                   407 non-null    object
 2   Storage                 407 non-null    int64
 3   RAM                     407 non-null    int64
 4   Screen Size (inches)    407 non-null    object
 5   Camera (MP)             407 non-null    object
 6   Battery Capacity (mAh)  407 non-null    int64
 7   Price ($)               407 non-null    object
dtypes: int64(3), object(5)
memory usage: 25.6+ KB

Sekarang kita akan mengecek gambaran umum dari dataframe menggunakan df.describe. Disini kita melihat perbedaan dengan hasil describe sebelumnya yang hanya menampilkan data statistik deskriptif dari kolom Battery Capacity (mAh) dan Storage saja, sedangkan describe sesudahnya juga menampilkan data statistik deskriptif dari kolom RAM

In [59]:
df.describe()

         Storage         RAM   Battery Capacity (mAh)
count  407.000000  407.000000              407.000000
mean   123.046683    5.837838             4676.476658
std     64.963160    2.431980              797.193713
min     32.000000    2.000000             1821.000000
25%     64.000000    4.000000             4300.000000
50%    128.000000    6.000000             5000.000000
75%    128.000000    8.000000             5000.000000
max    512.000000   16.000000             7000.000000

## Analisis Kolom Screen Size

### Penjelasan
Pada Analisis Kolom Screen Size ini kita tidak melakukan operasi seperti pada Analisis Kolom Storage dan Analisis Kolom RAM. Pada Analisis Kolom Screen Size ini kita mendeteksi nilai unique pada kolom Screen Size (inches), serta di record baris berapa yang mengandung nilai unique tersebut.

In [63]:
df.columns

Index(['Brand', 'Model', 'Storage ', 'RAM ', 'Screen Size (inches)',
       'Camera (MP)', 'Battery Capacity (mAh)', 'Price ($)'],
      dtype='object')

In [65]:
df['Screen Size (inches)'].unique()

array(['6.1', '6.8', '6.7', '6.67', '6.4', '6.55', '6.78', '6.43', '6.5',
       '6.62', '5.4', '6.2', '6.51', '6.6', '4.7', '6.58', '6.52', '6.44',
       '6.53', '6.56', '6.8 + 3.9', '4.5', '6.39', '5.9', '5.5', '6.81',
       '5.99', '6.82', '6.3', '6.22', '6', '6.35', '6.9', '6.76', '6.49',
       '6.72', '5.7', '6.47', '7.6 (unfolded)', '6.15', '6.57'],
      dtype=object)

In [67]:
df[df['Screen Size (inches)'] == '6.8 + 3.9']

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
88,LG,Wing,256,8,6.8 + 3.9,64MP + 13MP + 12MP,4000,$999

In [69]:
df[df['Screen Size (inches)'] == '7.6 (unfolded)']

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
373,Samsung,Galaxy Z Fold2 5G,256,12,7.6 (unfolded),12+12+12,4500,1999

## Analisis Kolom Price

In [75]:
## Pertama kita akan melihat nilai unik dari dataframe khususnya pada kolom Price
df['Price ($)'].unique()

array(['999', '1199', '899', '279', '799', '249', '699', '329', '449',
       '199', '299', '379', '179', '729', '599', '139', '189', '399',
       '259', '159', '229', '499', '129', '529', '369', '1099', '169',
       '99', '459', '239', '1299', '429', '659', '269', '359', '$799 ',
       '$399 ', '$699 ', '$329 ', '$999 ', '$549 ', '$1,299 ', '$899 ',
       '$449 ', '$319 ', '$269 ', '$349 ', '$279 ', '$249 ', '$299 ',
       '$969 ', '$1,199 ', '$149 ', '$139 ', '$99 ', '$199 ', '$169 ',
       '$499 ', '$179 ', '$219 ', '$229 ', '$239 ', '$109 ', '$189 ',
       '$389 ', '$309 ', '$369 ', '$129 ', '$849 ', '$469 ', '$209 ',
       '$119 ', '$339 ', '$429 ', '$159 ', '$379 ', '$289 ', '130', '749',
       '149', '969', '649', '349', '419', '1399', '1999', '119', '319',
       '1049'], dtype=object)

Hasil yang diberikan dari perintah df['Price (tanda dollar)'].unique di atas adalah berupa array dari nilai unik yang ada di kolom Price (tanda dollar). Jika kita melihat bahwa selain semua tipe data pada kolom Price (tanda dollar) masih bertipe object, ada ketidaksamaan isi dari kolom Price (tanda dollar). Dimana ada data yang mengandung tanda dollar, koma (,) dan spasi. Untuk hal ini maka perlu kita melakukan replace simbol-simbol tersebut pada semua data-data dari kolom Price (tanda dollar) yang masih mengandung simbol-simbol tersebut. Selain itu juga kita akan melakukan konversi ke dalam tipe data integer untuk data-data di kolom Price (tanda dollar).

In [78]:
df['Price ($)'] = df['Price ($)'].str.replace('$', '')
df['Price ($)'] = df['Price ($)'].str.replace(',', '')
df['Price ($)'] = df['Price ($)'].str.replace(' ', '')
df['Price ($)'] = df['Price ($)'].astype(int)

Sekarang kita akan mengecek tipe data Price dengan menggunakan perintah df.info

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Brand                   407 non-null    object
 1   Model                   407 non-null    object
 2   Storage                 407 non-null    int64
 3   RAM                     407 non-null    int64
 4   Screen Size (inches)    407 non-null    object
 5   Camera (MP)             407 non-null    object
 6   Battery Capacity (mAh)  407 non-null    int64
 7   Price ($)               407 non-null    int64
dtypes: int64(4), object(4)
memory usage: 25.6+ KB

Sekarang kita akan mengecek gambaran umum dari dataframe menggunakan df.describe. Disini kita melihat perbedaan dengan hasil describe sebelumnya hanya menampilkan data statistik deskriptif dari kolom Battery Capacity (mAh), Storage dan RAM saja, sedangkan describe hasil yang baru juga menampilkan data statistik deskriptif dari kolom Price

In [84]:
df.describe()

         Storage         RAM   Battery Capacity (mAh)    Price ($)
count  407.000000  407.000000              407.000000   407.000000
mean   123.046683    5.837838             4676.476658   408.314496
std     64.963160    2.431980              797.193713   299.684768
min     32.000000    2.000000             1821.000000    99.000000
25%     64.000000    4.000000             4300.000000   199.000000
50%    128.000000    6.000000             5000.000000   299.000000
75%    128.000000    8.000000             5000.000000   499.000000
max    512.000000   16.000000             7000.000000  1999.000000

# Sorting

## Penjelasan
Sorting merupakan kegiatan untuk mengurutkan data berdasarkan kolom tertentu, baik itu urut secara ascending maupun descending

In [88]:
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
0,Apple,iPhone 13 Pro,128,6,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256,12,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128,8,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128,6,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128,8,6.4,50 + 12.2,4614,799
...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649

In [90]:
# Berikut adalah kode untuk mengurutkan data-data pada kolom Battery Capacity (mAh) secara descending
df.sort_values(by = 'Battery Capacity (mAh)', ascending = False)

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
208,Samsung,Galaxy M62,128,8,6.7,64MP + 12MP + 5MP + 5MP,7000,429
334,Samsung,Galaxy M51,128,6,6.7,64+12+5+5,7000,449
205,Motorola,Moto G60,128,6,6.8,108MP + 8MP + 2MP,6000,299
35,Realme,C25s,128,4,6.5,13 + 2 + 2,6000,159
372,Motorola,Moto G9 Power,128,4,6.8,64+2+2,6000,229
...,...,...,...,...,...,...,...,...
32,Apple,iPhone SE (2nd Gen),64,3,4.7,12,1821,399
62,Apple,iPhone SE (2020),64,3,4.7,12,1821,399
289,Apple,iPhone SE (2020),64,3,4.7,12,1821,399
333,Apple,iPhone SE (2020),64,3,4.7,12,1821,399
379,Apple,iPhone SE (2020),128,3,4.7,12,1821,449

In [92]:
df.sort_values(by = ['Battery Capacity (mAh)', 'Price ($)'], ascending = [False, True])

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
208,Samsung,Galaxy M62,128,8,6.7,64MP + 12MP + 5MP + 5MP,7000,429
334,Samsung,Galaxy M51,128,6,6.7,64+12+5+5,7000,449
119,Realme,Narzo 50A,64,4,6.5,50MP + 2MP,6000,149
128,Nokia,C30,64,3,6.82,13MP + 2MP,6000,149
175,Realme,C25s,128,4,6.5,13MP + 2MP + 2MP,6000,149
...,...,...,...,...,...,...,...,...
32,Apple,iPhone SE (2nd Gen),64,3,4.7,12,1821,399
62,Apple,iPhone SE (2020),64,3,4.7,12,1821,399
289,Apple,iPhone SE (2020),64,3,4.7,12,1821,399
333,Apple,iPhone SE (2020),64,3,4.7,12,1821,399
379,Apple,iPhone SE (2020),128,3,4.7,12,1821,449

# Filtering

Filtering merupakan kegiatan untuk menyeleksi data berdasarkan kolom tertentu

In [96]:
df['Brand'].unique()

array(['Apple', 'Samsung', 'OnePlus', 'Xiaomi', 'Google', 'Oppo', 'Vivo',
       'Realme', 'Motorola', 'Nokia', 'Sony', 'LG', 'Asus', 'Blackberry',
       'CAT', 'Huawei'], dtype=object)

In [98]:
df[df['Brand'] == 'Xiaomi']
# perintah di atas untuk menampilkan data-data dari kolom Brand dengan values = Xiaomi

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
3,Xiaomi,Redmi Note 10 Pro,128,6,6.67,64 + 8 + 5 + 2,5020,279
7,Xiaomi,Poco X3 Pro,128,6,6.67,48 + 8 + 2 + 2,5160,249
15,Xiaomi,Mi 11 Lite 5G NE,128,6,6.55,64 + 8 + 5,4250,329
20,Xiaomi,Redmi 10 Prime,128,6,6.5,50 + 8 + 2 + 2,6000,179
24,Xiaomi,Redmi Note 10 Pro Max,128,6,6.67,108 + 8 + 5 + 2,5020,279
...,...,...,...,...,...,...,...,...
380,Xiaomi,Redmi 9C,64,3,6.53,13+2+2,5000,119
386,Xiaomi,Redmi Note 10 Pro,128,6,6.67,108+8+5+2,5020,329
389,Xiaomi,Redmi 9T,128,4,6.53,48+8+2+2,6000,199
397,Xiaomi,Poco M3,128,4,6.53,48+2+2,6000,149
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349

In [100]:
df[(df['Brand'] == 'Xiaomi') & (df['Price ($)'] < 200)].sort_values(by = 'Price ($)')
# perintah di atas untuk menampilkan data-data dari kolom Brand dengan values = Xiaomi dan kolom Price dengan values < 200. Hasilnya akan ditampilkan secara berurut berdasarkan kolom Price

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
380,Xiaomi,Redmi 9C,64,3,6.53,13+2+2,5000,119
218,Xiaomi,Redmi 9i,64,4,6.53,13MP,5000,139
397,Xiaomi,Poco M3,128,4,6.53,48+2+2,6000,149
304,Xiaomi,Redmi 9,64,4,6.53,13+8+5+2,5020,149
275,Xiaomi,Redmi 9,64,4,6.53,13MP + 8MP + 5MP + 2MP,5020,149
152,Xiaomi,Redmi 9 Activ,64,4,6.53,13MP + 2MP,5000,149
281,Xiaomi,Redmi Note 7,64,4,6.3,48MP + 5MP,4000,159
263,Xiaomi,Redmi 9 Power,64,4,6.53,48MP + 8MP + 2MP + 2MP,6000,169
364,Xiaomi,Poco M3,128,4,6.53,48+2+2,6000,179
269,Xiaomi,Redmi Note 8,64,4,6.3,48MP + 8MP + 2MP + 2MP,4000,179
20,Xiaomi,Redmi 10 Prime,128,6,6.5,50 + 8 + 2 + 2,6000,179
137,Xiaomi,Poco M3 Pro 5G,64,4,6.5,48MP + 2MP + 2MP,5000,179
31,Xiaomi,Redmi 10,128,4,6.5,50 + 8 + 2 + 2,5000,179
145,Xiaomi,Redmi 10 Prime,128,4,6.5,50MP + 8MP + 2MP + 2MP,6000,189
50,Xiaomi,Redmi 9 Power,128,4,6.53,48 + 8 + 2 + 2,6000,189
389,Xiaomi,Redmi 9T,128,4,6.53,48+8+2+2,6000,199
241,Xiaomi,Redmi 10 Prime,128,4,6.5,50MP + 8MP + 2MP + 2MP,6000,199
252,Xiaomi,Redmi Note 10,64,4,6.43,48MP + 8MP + 2MP + 2MP,5000,199
110,Xiaomi,Poco M3 Pro 5G,128,6,6.5,48MP + 2MP + 2MP,5000,199
61,Xiaomi,Poco M3 Pro 5G,64,4,6.5,48 + 2 + 2,5000,199
56,Xiaomi,Redmi 9T,128,4,6.53,48 + 8 + 2 + 2,6000,199
358,Xiaomi,Redmi 9T,128,4,6.53,48+8+2+2,6000,199
38,Xiaomi,Poco M3 Pro 5G,64,4,6.5,48 + 2 + 2,5000,199
210,Xiaomi,Redmi 10 Prime,128,6,6.5,50MP + 8MP + 2MP + 2MP,6000,199
235,Xiaomi,Redmi 9 Power,128,4,6.53,48MP + 8MP + 2MP + 2MP,6000,199

In [102]:
# filter menggunakan indeks
df.iloc[5:10, 1:4]

            Model  Storage   RAM
5       iPhone 13       128     4
6  Galaxy Z Flip3       256     8
7     Poco X3 Pro       128     6
8   Reno6 Pro+ 5G       128     8
9        X70 Pro+       256    12

# Tambah Kolom Baru

In [105]:
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
0,Apple,iPhone 13 Pro,128,6,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256,12,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128,8,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128,6,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128,8,6.4,50 + 12.2,4614,799
...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649

In [107]:
df['Battery dollar'] = df['Battery Capacity (mAh)'] / df['Price ($)']

In [109]:
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($),Battery dollar
0,Apple,iPhone 13 Pro,128,6,6.1,12 + 12 + 12,3095,999,3.098098
1,Samsung,Galaxy S21 Ultra,256,12,6.8,108 + 10 + 10 + 12,5000,1199,4.170142
2,OnePlus,9 Pro,128,8,6.7,48 + 50 + 8 + 2,4500,899,5.005562
3,Xiaomi,Redmi Note 10 Pro,128,6,6.67,64 + 8 + 5 + 2,5020,279,17.992832
4,Google,Pixel 6,128,8,6.4,50 + 12.2,4614,799,5.774718
...,...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049,4.099142
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349,11.919771
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099,3.354868
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429,9.382284
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649,6.933744

In [111]:
df.sort_values(by = 'Battery dollar', ascending = False)

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($),Battery dollar
273,Realme,C11,32,2,6.5,13MP + 2MP,5000,99,50.505051
216,Realme,C11 2021,32,2,6.52,8MP + 2MP,5000,99,50.505051
53,Realme,Narzo 50i,32,2,6.5,50 + 2,5000,99,50.505051
109,Motorola,Moto E7i Power,32,2,6.5,13MP + 2MP,5000,99,50.505051
250,Realme,C11 2021,32,2,6.5,8MP + 2MP,5000,99,50.505051
...,...,...,...,...,...,...,...,...,...
361,Huawei,P40 Pro+,512,8,6.58,50+40+12+3D,4200,1399,3.002144
338,Apple,iPhone XS Max,256,4,6.5,12+12,3174,1099,2.888080
384,Apple,iPhone 12 Pro,128,6,6.1,12+12+12,2815,999,2.817818
369,Apple,iPhone 12 mini,256,4,5.4,12+12,2227,899,2.477197
373,Samsung,Galaxy Z Fold2 5G,256,12,7.6 (unfolded),12+12+12,4500,1999,2.251126

# Grouping

In [114]:
# hitung rata2 harga untuk setiap Brand
df.groupby('Brand').agg(rata2_harga = ('Price ($)', 'mean')).sort_values(by = 'rata2_harga')

            rata2_harga
Brand
Realme       206.906977
Nokia        244.714286
Motorola     278.130435
Xiaomi       282.880597
CAT          299.000000
Vivo         323.000000
Oppo         376.142857
Samsung      480.405063
Blackberry   499.000000
LG           615.666667
OnePlus      644.333333
Google       699.000000
Apple        745.666667
Huawei       783.166667
Asus         874.000000
Sony        1299.000000

In [116]:
df.groupby('Brand').agg(rata2_harga = ('Price ($)', 'mean'), rata2_battery_dollar = ('Battery dollar', 'mean')).\
    sort_values(by = 'rata2_battery_dollar', ascending = False)

            rata2_harga  rata2_battery_dollar
Brand
Realme       206.906977             29.611341
Nokia        244.714286             24.147764
Xiaomi       282.880597             21.741245
Motorola     278.130435             21.486571
Vivo         323.000000             19.723246
Oppo         376.142857             16.671770
Samsung      480.405063             16.272994
CAT          299.000000             14.046823
OnePlus      644.333333              8.203581
LG           615.666667              8.027519
Huawei       783.166667              7.517468
Blackberry   499.000000              7.517004
Google       699.000000              5.879461
Asus         874.000000              5.712984
Apple        745.666667              4.064740
Sony        1299.000000              3.464203

# Pivot Table

In [119]:
df.pivot_table(index = 'Brand', values = 'Price ($)', aggfunc = 'mean')

              Price ($)
Brand
Apple        745.666667
Asus         874.000000
Blackberry   499.000000
CAT          299.000000
Google       699.000000
Huawei       783.166667
LG           615.666667
Motorola     278.130435
Nokia        244.714286
OnePlus      644.333333
Oppo         376.142857
Realme       206.906977
Samsung      480.405063
Sony        1299.000000
Vivo         323.000000
Xiaomi       282.880597

# Lambda Function

In [122]:
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($),Battery dollar
0,Apple,iPhone 13 Pro,128,6,6.1,12 + 12 + 12,3095,999,3.098098
1,Samsung,Galaxy S21 Ultra,256,12,6.8,108 + 10 + 10 + 12,5000,1199,4.170142
2,OnePlus,9 Pro,128,8,6.7,48 + 50 + 8 + 2,4500,899,5.005562
3,Xiaomi,Redmi Note 10 Pro,128,6,6.67,64 + 8 + 5 + 2,5020,279,17.992832
4,Google,Pixel 6,128,8,6.4,50 + 12.2,4614,799,5.774718
...,...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049,4.099142
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349,11.919771
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099,3.354868
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429,9.382284
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649,6.933744

In [124]:
def get_category(price):
    category = ''
    if price <= 500:
        category = 'MURAH'
    else:
        category = 'MAHAL'
    return category

In [126]:
get_category(1000)

'MAHAL'

In [128]:
for i in range(len(df)):
    df.loc[i, 'category'] = get_category(df.loc[i, 'Price ($)'])

In [130]:
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($),Battery dollar,category
0,Apple,iPhone 13 Pro,128,6,6.1,12 + 12 + 12,3095,999,3.098098,MAHAL
1,Samsung,Galaxy S21 Ultra,256,12,6.8,108 + 10 + 10 + 12,5000,1199,4.170142,MAHAL
2,OnePlus,9 Pro,128,8,6.7,48 + 50 + 8 + 2,4500,899,5.005562,MAHAL
3,Xiaomi,Redmi Note 10 Pro,128,6,6.67,64 + 8 + 5 + 2,5020,279,17.992832,MURAH
4,Google,Pixel 6,128,8,6.4,50 + 12.2,4614,799,5.774718,MAHAL
...,...,...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049,4.099142,MAHAL
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349,11.919771,MURAH
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099,3.354868,MAHAL
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429,9.382284,MURAH
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649,6.933744,MAHAL

In [132]:
df['category_lambda'] = df['Price ($)'].apply(lambda x: 'MURAH' if x <= 500 else ('SEDANG' if x<= 1000 else 'MAHAL'))