# Deskripsi

## Deskripsi Project
Project ini merupakan salah satu tugas Mini Project pada Kelas Data Science & AI Fundamentals Batch 42 yang diselenggarakan oleh DigitalSkola. Mini Project ini dikerjakan oleh : Khadafi Zubaidi.

Dalam project ini dijelaskan mengenai langkah-langkah untuk membersihkan data, menampilkan data, serta melakukan analisis data eksploratif menggunakan bahasa pemrograman Python dan file data berekstensi csv.

# Import Library

## Penjelasan
Library yang digunakan dalam project ini adalah Pandas. Pandas adalah pustaka Python yang digunakan untuk mengolah data, seperti menganalisis, membersihkan, menjelajahi, dan memanipulasi data. Nama Pandas berasal dari singkatan "Panel Data" dan "Python Data Analysis"

In [6]:
import pandas as pd

# Memanggil Data

## Penjelasan
Setelah dilakukan import library pandas, selanjutnya kita akan memanggil data-data pada file csv kemudian disimpan ke dalam variabel df (dataframe). Hal ini diperlukan untuk pengelolaan data selanjutnya.

In [11]:
df = pd.read_csv('Mobile_phone_price.csv')

Sekarang kita tampilkan isi dari variabel df

In [14]:
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
0,Apple,iPhone 13 Pro,128 GB,6 GB,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256 GB,12 GB,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128 GB,8 GB,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128 GB,6 GB,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128 GB,8 GB,6.4,50 + 12.2,4614,799
...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649

# Informasi Umum Dataframe

## Penjelasan
Untuk melihat informasi umum dari dataframe (df) kita menggunakan metode :
1.   df.shape : untuk mengetahui jumlah baris dan kolom dataframe tersebut
2.   df.info : untuk mengetahui jumlah kolom, label kolom, tipe data setiap kolom
3.   df.describe : untuk mengetahui gambaran umum dari dataframe berupa statistik deskriptif, seperti : jumlah (count), rata-rata (mean), deviasi standar (std), nilai minimum (min), persentil ke-25 (Q1), median (persentil ke-50 atau Q2), persentil ke-75 (Q3) dan nilai maksimum (max)
4.   df.columns : untuk mengetahui judul setiap kolom pada dataframe tersebut

In [19]:
df.shape

(407, 8)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Brand                   407 non-null    object
 1   Model                   407 non-null    object
 2   Storage                 407 non-null    object
 3   RAM                     407 non-null    object
 4   Screen Size (inches)    407 non-null    object
 5   Camera (MP)             407 non-null    object
 6   Battery Capacity (mAh)  407 non-null    int64
 7   Price ($)               407 non-null    object
dtypes: int64(1), object(7)
memory usage: 25.6+ KB

In [23]:
df.describe()

       Battery Capacity (mAh)
count              407.000000
mean              4676.476658
std                797.193713
min               1821.000000
25%               4300.000000
50%               5000.000000
75%               5000.000000
max               7000.000000

In [25]:
df.columns

Index(['Brand', 'Model', 'Storage ', 'RAM ', 'Screen Size (inches)',
       'Camera (MP)', 'Battery Capacity (mAh)', 'Price ($)'],
      dtype='object')

# Analisis

## Penjelasan
Pada bagian ini kita akan melakukan beberapa analisis yaitu : Analisis Kolom Storage, Analisis Kolom RAM, Analisis Kolom Screen Size dan Analisis Kolom Price


---

## Analisis Kolom Storage

In [30]:
## Pertama kita akan melihat nilai unik dari dataframe khususnya pada kolom Storage
df['Storage '].unique()

array(['128 GB', '256 GB', '64 GB', '32 GB', '128GB', '256GB', '64GB',
       '32GB', '256', '64', '128', '512', '32'], dtype=object)

Hasil yang diberikan dari perintah df['Storage '].unique() di atas adalah berupa array dari nilai unik yang ada di kolom Storage. Jika kita melihat bahwa **selain semua tipe data pada kolom Storage masih bertipe object, ada ketidaksamaan isi dari kolom Storage. Dimana ada data yang mengandung kata GB dan tidak. Untuk hal ini maka perlu kita melakukan penghapusan kata GB**. Kode berikut ini adalah contohnya :

In [33]:
s = '128 GB' # Kita definisikan sebuah variabel s dengan nilai string 128<spasi>GB
s = s.replace(' GB', '') # mereplace string '<spasi>GB' dari string variabel s untuk kemudian disimpan kembali dalam variabel s
s # tampilkan isi dari variabel s, hasil yang diberikan adalah 128 saja tanpa GB

'128'

In [35]:
type(s) # cek tipe data dari variabel s

str

Kode berikut berfungsi untuk menghapus kata GB pada data-data dari kolom Storage yang masih mengandung GB. Selain itu juga kita akan melakukan konversi ke dalam tipe data integer untuk data-data di kolom Storage. Konversi ini dibutuhkan agar ketika dilakukan describe pada kolom Storage, dihasilkan gambaran umum berupa statistik deskriptif, seperti : jumlah (count), rata-rata (mean), deviasi standar (std), nilai minimum (min), persentil ke-25 (Q1), median (persentil ke-50 atau Q2), persentil ke-75 (Q3) dan nilai maksimum (max).

In [39]:
df['Storage '] = df['Storage '].str.replace(' ', '')
df['Storage '] = df['Storage '].str.replace('GB', '')
df['Storage '] = df['Storage '].astype(int)

In [41]:
df

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh),Price ($)
0,Apple,iPhone 13 Pro,128,6 GB,6.1,12 + 12 + 12,3095,999
1,Samsung,Galaxy S21 Ultra,256,12 GB,6.8,108 + 10 + 10 + 12,5000,1199
2,OnePlus,9 Pro,128,8 GB,6.7,48 + 50 + 8 + 2,4500,899
3,Xiaomi,Redmi Note 10 Pro,128,6 GB,6.67,64 + 8 + 5 + 2,5020,279
4,Google,Pixel 6,128,8 GB,6.4,50 + 12.2,4614,799
...,...,...,...,...,...,...,...,...
402,Samsung,Galaxy Note20 5G,128,8,6.7,12+64+12,4300,1049
403,Xiaomi,Mi 10 Lite 5G,128,6,6.57,48+8+2+2,4160,349
404,Apple,iPhone 12 Pro Max,128,6,6.7,12+12+12,3687,1099
405,Oppo,Reno3,128,8,6.4,48+13+8+2,4025,429
406,Samsung,Galaxy S10 Lite,128,6,6.7,48+12+5,4500,649

Sekarang kita akan mengecek tipe data Storage dengan menggunakan perintah df.info

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Brand                   407 non-null    object
 1   Model                   407 non-null    object
 2   Storage                 407 non-null    int64
 3   RAM                     407 non-null    object
 4   Screen Size (inches)    407 non-null    object
 5   Camera (MP)             407 non-null    object
 6   Battery Capacity (mAh)  407 non-null    int64
 7   Price ($)               407 non-null    object
dtypes: int64(2), object(6)
memory usage: 25.6+ KB

Sekarang kita akan mengecek gambaran umum dari dataframe menggunakan df.describe. Disini kita melihat **perbedaan dengan hasil describe pada kode sebelumnya yang hanya menampilkan data statistik deskriptif dari kolom Battery Capacity (mAh) saja, sedangkan describe yang baru juga menampilkan data statistik deskriptif dari kolom Storage**

In [47]:
df.describe()

         Storage   Battery Capacity (mAh)
count  407.000000              407.000000
mean   123.046683             4676.476658
std     64.963160              797.193713
min     32.000000             1821.000000
25%     64.000000             4300.000000
50%    128.000000             5000.000000
75%    128.000000             5000.000000
max    512.000000             7000.000000